-- CLASE 6
-- TEMA INFORMES
use jugos_ventas;
SELECT * FROM facturas;
SELECT * FROM items_facturas;
SELECT * FROM tabla_de_clientes;
SELECT * FROM tabla_de_productos;
SELECT * FROM tabla_de_vendedores;
-- --------------------------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM facturas;
SELECT * FROM items_facturas;

SELECT F.DNI, F.FECHA_VENTA, IFa.CANTIDAD FROM facturas F
INNER JOIN items_facturas IFa
ON F.NUMERO = IFa.NUMERO;

-- POR FECHA Y DIA LAS VENTAS Y FACTURAS
SELECT F.DNI, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, IFa.CANTIDAD FROM facturas F
INNER JOIN items_facturas IFa
ON F.NUMERO = IFa.NUMERO;

-- REALIZAR CONSUTAS AL CLIENTE POR MES
-- CANTIDAD DE VENTAS POR MES ÀRA CADA CIENTE
SELECT F.DNI, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, SUM(IFa.CANTIDAD) AS SUMA_CANTIDAD FROM facturas F
INNER JOIN items_facturas IFa
ON F.NUMERO = IFa.NUMERO
GROUP BY F.DNI, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y");

-- LIMITE DE VENTAS PARA CADA CLIENTE
SELECT * FROM tabla_de_clientes TC;


-- Complementa este informe listando solamente a los que tuvieron ventas inválidas 
-- calcula la diferencia entre el límite de venta máximo y la cantidad vendida en porcentuales.
SELECT A.DNI, A.NOMBRE, A.MES_AÑO, A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
CASE
   WHEN  (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) <= 0 THEN 'Venta Válida'
   ELSE 'Venta Inválida'
END AS STATUS_VENTA, ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100,2) AS PORCENTAJE
 FROM( SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, 
						MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA  FROM facturas F 
                        INNER JOIN 
                        items_facturas IFa
						ON F.NUMERO = IFa.NUMERO
INNER JOIN tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y"))A
WHERE (A.CANTIDAD_MAXIMA - A.CANTIDAD_VENDIDA) < 0;

-- -------------------------------------------------------------------------------
-- LIMITE DE VENTAS PARA CADA CLIENTE ( VOLUMEN E CECILITROS)
SELECT DNI, NOMBRE, VOLUMEN_DE_COMPRA FROM tabla_de_clientes TC;

SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, SUM(IFa.CANTIDAD_VENDIDA) AS SUMA_CANTIDAD, 
		MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA FROM facturas F
INNER JOIN items_facturas IFa
ON F.NUMERO = IFa.NUMERO
INNER JOIN tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y");

-- SE CREARA UNA CONSULTA, CON SU SUBCONSULTA PARA TENER LA INFORMACION MAS COMPRENSIBLE

SELECT A.DNI, A.NOMBRE, A.MES_AÑO, A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA FROM (
	SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, 
		MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA FROM facturas F
	INNER JOIN items_facturas IFa
	ON F.NUMERO = IFa.NUMERO
	INNER JOIN tabla_de_clientes TC
	ON TC.DNI = F.DNI
	GROUP BY F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") ) A;
    
-- HACER EL INFORME MAS COMPRENSIBLE
SELECT A.DNI, A.NOMBRE, A.MES_AÑO, A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA, 
CASE 
	WHEN (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) <= 0 THEn 'Venta Valida'
    else 'Venta Invalida'
END AS STATUS_VENTA
FROM (
	SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, 
		MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA FROM facturas F
	INNER JOIN items_facturas IFa
	ON F.NUMERO = IFa.NUMERO
	INNER JOIN tabla_de_clientes TC
	ON TC.DNI = F.DNI
	GROUP BY F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") ) A;

-- lista solamente a los que tuvieron ventas inválidas en el año 2018 excediendo más del 50% de su límite permitido por mes. 
-- Calcula la diferencia entre el límite de venta máximo y la cantidad vendida, en porcentuales.
SELECT A.DNI, A.NOMBRE, A.MES_AÑO, A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
	CASE
	   WHEN  (A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA) <= 0 THEN 'Venta Válida'
	   ELSE 'Venta Inválida'
	END AS STATUS_VENTA, ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100,2) AS PORCENTAJE
			 FROM(SELECT F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y") AS MES_AÑO, 
			SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA  
			FROM facturas F 
			INNER JOIN items_facturas IFa
			ON F.NUMERO = IFa.NUMERO
			INNER JOIN tabla_de_clientes TC
			ON TC.DNI = F.DNI
			GROUP BY F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, "%m - %Y"))A
WHERE (A.CANTIDAD_MAXIMA - A.CANTIDAD_VENDIDA) < 0 AND ROUND((1 - (A.CANTIDAD_MAXIMA/A.CANTIDAD_VENDIDA)) * 100,2) > 50
AND A.MES_AÑO LIKE "%2018";

-- -------------------------------------------------------------------------------------------------------------------------------------
-- INFORME DE TOTAL DE VENTAS POR SABOR 2016, CANTIDAD DE LITOS Y EL PORCENTAJE DE VENTAS EN ORDEN DE MAYOT A MENOR
use jugos_ventas;
SELECT * FROM facturas;
SELECT * FROM items_facturas;
SELECT * FROM tabla_de_clientes;
SELECT * FROM tabla_de_productos;
SELECT * FROM tabla_de_vendedores;
-- 
SELECT P.SABOR, IFa.CANTIDAD, F.FECHA_VENTA FROM tabla_de_productos P 
INNER JOIN items_facturas IFa
ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
ON F.NUMERO = IFa.NUMERO;

-- CANTIDAD VENDIDAD POR SABOR AÑO 2016
SELECT P.SABOR, SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM tabla_de_productos P 
INNER JOIN items_facturas IFa
ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
ON F.NUMERO = IFa.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY P.SABOR,YEAR(F.FECHA_VENTA)
ORDER BY SUM(IFa.CANTIDAD) DESC;
-- CANTIDAD TOTAL POR AÑO
SELECT  SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM tabla_de_productos P 
INNER JOIN items_facturas IFa
ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
ON F.NUMERO = IFa.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY YEAR(F.FECHA_VENTA);
-- ----------------------------------------------------------------------------------------------------------
-- CANTIDAD VENDIDAD POR SABOR AÑO 2016
SELECT * FROM (
SELECT P.SABOR, SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM tabla_de_productos P 
INNER JOIN items_facturas IFa
ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
ON F.NUMERO = IFa.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY P.SABOR,YEAR(F.FECHA_VENTA)
ORDER BY SUM(IFa.CANTIDAD) DESC) VENTAS_SABOR
INNER JOIN (
SELECT  SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM tabla_de_productos P 
INNER JOIN items_facturas IFa
ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
ON F.NUMERO = IFa.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY YEAR(F.FECHA_VENTA)) VENTA_TOTAL
ON VENTA_TOTAL.AÑO = VENTAS_SABOR.AÑO;

-- ----------------------------------------------------------------------------------------------------------
-- CANTIDAD VENDIDAD POR SABOR AÑO 2016
SELECT VENTAS_SABOR.SABOR, VENTAS_SABOR.AÑO, VENTAS_SABOR.CANTIDAD_TOTAL, 
		ROUND((VENTAS_SABOR.CANTIDAD_TOTAL / VENTA_TOTAL.CANTIDAD_TOTAL) * 100, 2) AS PORCENTAJE FROM (
	SELECT P.SABOR, SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM tabla_de_productos P 
	INNER JOIN items_facturas IFa
	ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
	INNER JOIN facturas F
	ON F.NUMERO = IFa.NUMERO
	WHERE YEAR(F.FECHA_VENTA) = 2016
	GROUP BY P.SABOR,YEAR(F.FECHA_VENTA)
	ORDER BY SUM(IFa.CANTIDAD) DESC) VENTAS_SABOR
INNER JOIN (
	SELECT  SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM tabla_de_productos P 
	INNER JOIN items_facturas IFa
	ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
	INNER JOIN facturas F
	ON F.NUMERO = IFa.NUMERO
	WHERE YEAR(F.FECHA_VENTA) = 2016
	GROUP BY YEAR(F.FECHA_VENTA)) VENTA_TOTAL
ON VENTA_TOTAL.AÑO = VENTAS_SABOR.AÑO
ORDER BY VENTAS_SABOR.CANTIDAD_TOTAL DESC;

-- Modifica el informe pero ahora para ver el ranking de las ventas por tamaño.
SELECT VENTAS_TAMANO.TAMANO, VENTAS_TAMANO.AÑO, VENTAS_TAMANO.CANTIDAD_TOTAL,
		ROUND((VENTAS_TAMANO.CANTIDAD_TOTAL/VENTA_TOTAL.CANTIDAD_TOTAL)*100,2) AS PORCENTAJE 
    FROM (
		SELECT P.TAMANO, SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL, 
				YEAR(F.FECHA_VENTA) AS AÑO FROM tabla_de_productos P
		INNER JOIN items_facturas IFa
		ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
		INNER JOIN facturas F
		ON F.NUMERO = IFa.NUMERO
		WHERE YEAR(F.FECHA_VENTA) = 2016
		GROUP BY P.TAMANO, YEAR(F.FECHA_VENTA)
		ORDER BY SUM(IFa.CANTIDAD) DESC) VENTAS_TAMANO
INNER JOIN (
		SELECT SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL, 
			YEAR(F.FECHA_VENTA) AS AÑO FROM tabla_de_productos P
		INNER JOIN items_facturas IFa
		ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
		INNER JOIN facturas F
		ON F.NUMERO = IFa.NUMERO
		WHERE YEAR(F.FECHA_VENTA) = 2016
		GROUP BY YEAR(F.FECHA_VENTA)) VENTA_TOTAL		
ON VENTA_TOTAL.AÑO = VENTAS_TAMANO.AÑO
ORDER BY VENTAS_TAMANO.CANTIDAD_TOTAL DESC;