/*
		CLASE 5 STORED PROCEDURES Y TRIGGERS
*/

USE empresa;
SELECT * FROM clientes;
SELECT * FROM productos;
SELECT * FROM vendedores;
SELECT * FROM facturas;
SELECT * FROM items;

		SELECT A.FECHA, SUM(B.CANTIDAD * B.PRECIO) AS FACTURACION FROM facturas A
	INNER JOIN items B
    ON A.NUMERO = B.NUMERO
    WHERE A.FECHA = '20210619'
    GROUP BY A.FECHA;
    
    CALL sp_venta('20210619', 20, 100);
    
    -- alcula el valor del impuesto pago en el año de 2021 redondeando al mayor entero.
SELECT YEAR(FECHA), CEIL(SUM(IMPUESTO * (CANTIDAD * PRECIO))) AS RESULTADO FROM facturas F
INNER JOIN items I 
ON F.NUMERO = I.NUMERO
WHERE YEAR(FECHA) = 2021
GROUP BY YEAR(FECHA);

/*
mejorando trigers
		se creara tabla de facturacion y creara trugers para cada comando dml
*/

CREATE TABLE facturacion(
FECHA DATE NULL,
VENTA_TOTAL FLOAT
);

SELECT * FROM facturacion;

--  ZONA DE TRIGGERS
	-- TRIGGER DE INSERT
DELIMITER //
CREATE TRIGGER TG_FACTURACION_INSERT 
AFTER INSERT ON items
FOR EACH ROW BEGIN
  DELETE FROM facturacion;
  INSERT INTO facturacion
  SELECT A.FECHA, SUM(B.CANTIDAD * B.PRECIO) AS VENTA_TOTAL
  FROM facturas A
  INNER JOIN
  items B
  ON A.NUMERO = B.NUMERO
  GROUP BY A.FECHA;
END //
	-- TRIGGER DE DELETE
DELIMITER //
CREATE TRIGGER TG_FACTURACION_DELETE
AFTER DELETE ON items
FOR EACH ROW BEGIN
  DELETE FROM facturacion;
  INSERT INTO facturacion
  SELECT A.FECHA, SUM(B.CANTIDAD * B.PRECIO) AS VENTA_TOTAL
  FROM facturas A
  INNER JOIN
  items B
  ON A.NUMERO = B.NUMERO
  GROUP BY A.FECHA;
END //

	-- TRIGGER DE UPDATE
DELIMITER //
CREATE TRIGGER TG_FACTURACION_UPDATE
AFTER UPDATE ON items
FOR EACH ROW BEGIN
  DELETE FROM facturacion;
  INSERT INTO facturacion
  SELECT A.FECHA, SUM(B.CANTIDAD * B.PRECIO) AS VENTA_TOTAL
  FROM facturas A
  INNER JOIN
  items B
  ON A.NUMERO = B.NUMERO
  GROUP BY A.FECHA;
END //

SELECT * FROM facturacion;

CALL sp_venta('20210621', 10, 100);


SELECT * FROM facturacion WHERE FECHA = '20210621';


 -- SE ELIMAN LOS TRIGERRSA CREADOS PARA SU CORRECCION
DROP TRIGGER TG_FACTURACION_INSERT;
DROP TRIGGER TG_FACTURACION_DELETE;
DROP TRIGGER TG_FACTURACION_UPDATE;

--  MODIFICACION DE TRIGGERS
	-- TRIGGER DE INSERT
DELIMITER //
CREATE TRIGGER TG_FACTURACION_INSERT 
AFTER INSERT ON items
FOR EACH ROW BEGIN
	CALL sp_triggers;
END //
	-- TRIGGER DE DELETE
DELIMITER //
CREATE TRIGGER TG_FACTURACION_DELETE
AFTER DELETE ON items
FOR EACH ROW BEGIN
	CALL sp_triggers;
END //

	-- TRIGGER DE UPDATE
DELIMITER //
CREATE TRIGGER TG_FACTURACION_UPDATE
AFTER UPDATE ON items
FOR EACH ROW BEGIN
	CALL sp_triggers;
END //