SELECT  * FROM tbcliente;
SELECT  * FROM  tbproducto;

SELECT  * FROM tbcliente;
SELECT DNI, NOMBRE, DIRECCION1, DIRECCION2, BARRIO, CIUDAD, ESTADO, CP, FECHA_NACIMIENTO, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA 
		FROM tbcliente;

SELECT DNI, NOMBRE FROM tbcliente;

SELECT NOMBRE,SEXO, EDAD, DIRECCION1 FROM tbcliente;

SELECT NOMBRE AS Nombre_completo,SEXO As Genero, EDAD AS Años, DIRECCION1 AS Domicilio FROM tbcliente;

SELECT NOMBRE AS Nombre_completo,SEXO As Genero, EDAD AS Años, DIRECCION1 AS Domicilio 
		FROM tbcliente LIMIT 6;


SELECT  * FROM tbcliente WHERE EDAD >27;
SELECT  * FROM tbcliente WHERE EDAD < 27;
SELECT  * FROM tbcliente WHERE EDAD <> 26;
SELECT  * FROM tbcliente WHERE NOMBRE > 'Erica Carvajo';
SELECT  * FROM tbproducto WHERE PRECIO_LISTA = 28.51;
SELECT  * FROM tbproducto WHERE PRECIO_LISTA < 28.51;
SELECT  * FROM tbproducto WHERE PRECIO_LISTA >= 28.51;
SELECT  * FROM tbproducto WHERE PRECIO_LISTA BETWEEN 28.49 AND 28.52;

SELECT  * FROM tbcliente;
SELECT  * FROM tbcliente WHERE FECHA_NACIMIENTO = '1995-01-13';
SELECT  * FROM tbcliente WHERE FECHA_NACIMIENTO < '1995-01-13';
SELECT  * FROM tbcliente WHERE FECHA_NACIMIENTO > '1995-01-13';