/*
CLASE 3 TUNNING
		"PONER A PUNTO PARA MEJORAR SU DESEMPEÑO"
        
	-- 4 FORMAS DE CONFIGURAR EL AMBIENTE DE MYSQL PARA HACE RK TUNNING
			*** ESQUEMAS, INDICES, VARIABLES INTERNS DE MYSQL(MYSQLD)  Y HARDWARE/SISTEMA OPERATIVO
				- HARDWARE
					1
                    A)- TRABAJAR CON SISTEMAS OPERATIVOS DE 64-BITS(MYSQL PUEDE USARIAS VARIOS PROCESADORES EN PARALELO Y PUEDE LLEGAR A CONSUMIR TODA LA CAPCIDAD DE MEMORIA DE LA PC)
                    B) - CONFIGURACION DE LA RAM(EXISTE UN PARAMETRO INTERNO QUE NOS PERIMTE INDICAR EL MAXIMO DE RAM QUE NUESTROS PROCESOS PODRAN CONSUMIR
													OBS- NO EXCEDER DEL 50% DE RAM DISPONIBLE EN LA MAQUINA O SERVIDOR)
						EJEMPLO "1 BBDD DE 1GB NO VA A CONSUMIR MAS DE 5GB DE RAM, PERO EN UN AMBIENTE REAL NO HABRA SOLO UNA CONEXION EJECUTANDO OPERACIONES EN LA BASE
									( DEPENDIENDO DE LA MANERA COMO SE UTILICE LA BBDD, 8GB DE RAN SERA POCO)"
					C) - TIPO DE LECTURA DE DISCO: ESTA ALMANCENADO EN HDD/SS?
							HOY EN DIA EXISTEM SCSI, SATA, SAS
					D)- USO DEL CONTROLADO DE DISCO RAID(0,1,5 Y 10). SON EMPLEADOS PARA LA SEGURIDAD DE LA BBDD
						
                        RAID0: DIVIDE LOS DATOS EN DOS HD DIFERENTERS, AUNQUE OBSERVAMOS TAN SOLO 1 DRIVE Y EL SISTEMA OPERATIVO DIVIDE EL DATO EN LOS DISCOS 
                        RAID1: UNO DE LOS HD ES COPIA DEL OTRO (LO QUE SE HAGA EN UN DISCO AUTOMATICAMENTE SE REPRODUCE EN EL OTRO)
                        RAID5: DIVIDE LOS DATOS EN MAS DE DOS HD, AUNQUE OBSERVEMOS TAN SOLO 1 DRIVE Y EL SISTEMA OPERATIVO DIVIDE EL DATO EN TODPOS LOS DISCOS
                        RAID10: LOS HD TIENE ESPEJOS( LO QUE SE HAGA EN DISCO AUTOMATICAMENTE SE REPDOUCE EN US DISCO ESPEJO)
					
                    AUNQUE RADI 1 Y 10 GSTAN MAS ESPACIO FISICO CON REDUNDANCIA, SON MAS SEGUROS POR QUE HAY BACKUP DISPONIBLES
	
    --- VARIABLES DE AMBIENTE DE MYSQL
		--- SON VARIABLES QUE SE DECLARAN AFUERA DEL PROGRMA PARA QUE AL MOMENTO DE SU INICIALIZACION QUEDEN PREDEFINIDOS  DIVERSOS PARAMETROS DE FUNCIONAMIENTO
        --- EXISTEN + 250  VARIABLES DE AMBIENTE EN MYSQL. SUFRE MODIFICACIONES CON CADA NUEVA VERSION
			--- SHOW STATUS MUESTRA LOS VALORES ACTUALES DE LAS VARIABLES DE AMBIENTE
            -- 2 TIPOS DE VARIABLES:  
				--- GLOBAL SE APLICA PARA TODO EL ENTORNO MYSQL
				--- SESSION SOLO SE EJECUTAN PARA LA CONEXION ACTUAL
			--- MY.INI(LINUX MY.CNF) DOS DIRECTIVAS [MYSQLD] [CLIENT0]
         
*/
SHOW GLOBAL STATUS LIKE 'Created_tmp_disk_tables' , 'Created_tmp_tables';

SHOW GLOBAL STATUS LIKE 'Created_tmp_tables';

SHOW GLOBAL VARIABLES LIKE 'tmp_table_size';

SET GLOBAL tmp_table_size =  52283072;


/*
	MECANISMOS DE ALMACENAMIENTO
		-- FORMA DE ALMCENAR INFORMACION EN LAS TABLAS(RECURSOS MAS EXCLUSIVOS DENTRO DE LA BBDD)
        -- MYSQL 8.0 COMMUNITY DISPONE DE 9 MECANISMOS PARA ALAMCENAR DATOS EN LAS TABLAS( UNA MISMA BBDD PUEDE USAR DIVERSOS MECANISMOS EN SUS TABLAS)
				-- ENGINE: ESEL PARAMETRO QUE INDICA EL MECANISMO DE ALMACENAMIENTO EMPLEADO EN LAS TABLAS
                -- LOS 3 PRINCIPALES ENGINES SON:   MYISAM, INNODB Y MEMOERY
              -------------MECANISMOS DE ALMACENAMIENTO PARA TABLAS MYISAM----------------------------  
			MYISAM: NO ES TRANSACCIONAL (NO ESTA DISEÑADO PARA QUE VARIOS USUARIOS REALICEN OPERACIONES EN LAS TABLAS SIMULTANEAMENTE)
				-- SOLAMENTE ÈR,OTE EL BLOQUEO A NIVEL DE TABLA. (LECTURA MAS RAPDIA)
                -- RECOMENDABLE PARA TABLAS QUE NO ESTAN COMBIANDO CONTINUAMENTE
                -- LA CLAVE EXTERNA NO SPORTA FULL TEXTX
                -- ALMACENA DATOS DE MANERA MAS COMPACTA(OPTIMIZA ESPACIO DE ALMACENAMIENTO)
                -- IMPLEMENTA IDNCES HAS Y  BTREE(VENTAJA)
                -- KEY_BUFFER_SIZE: DETERMIA EL TAMAÑO DE CAHCE PRA ALMACENAR LOS UNDCUCES DE MYISAM,VARIA DESDE 8MB HASTA 4GB DE ACUERDO CON EL SISTERMA 
                -- CONCURRENTE_INSERT: COMPORTAMIENTO DE INSERCCION CONCURRENTES DENTRO DE UNA TABLA CON MYISAM
					--- 0 = INSERCCIONES SIMULTANEAS DESACTIVADAS
                    --- 1 = INSERCCIONES SIMULTANEAS SIN INTERVALO DE DATOS (AL MISMO TIEMPO)
                    --- 2 = INSERCCIONES SIMULTANEAS CON INTERVALO DE DATOS
				-- DELAY_KEY_WRITE: ATRASO ENTRE LA ACTUALIZACION DE INDICES Y EL MOMENTO EN QUE SE CREA LA TABLA (ESPERA A QUE TODOS LOS REGISTROS SEAN alte
									INSERADOS PARA DE ACTUALIZA LOS INDICES  => COMNSISTENCIA - RAPIDEZ)
				-- MAX_WRIET_LOCK_COUNT : DETERMINA EL NUMERO DE GRABACIONES EN LAS TABLAS QUE TENDRAN PRECEDENCIA A LAS LECTURAS( PRIORIZAR LA CANTIDAD DE GRABACIONES		
														QUE SE REALIZARIN ANTES DE LAS LECTURAS EN VARIAS CONEXIONES)
				-- PRELOAD_BUFFER_SIZE: TAMAÑO DEL BUFFER A SER USADO ANTES DE CARGAR LOS INDICES DE CACHE DE CLAVES DE LAS TABLAS: 32KB
                
		*** OBSERVACION: EL USO DE ESTAS VARIABLES DE AMBIENTE SE REALIZARA EN LA MEDIDA QUE EL DBA ENTIENDA MEJOR SU AMBIENTE Y LOS MECANISMO DE MYISAM
				ES RECOMENDABLE UTILIZAR LA CONFIGURACION POR DEFECTO AL USAR EL MECANISMO MYISAM
                
		--------------- MYISAM- APLICACIONES-----------------------------------
        - MYISAMCHK: ANALIZA, OPTIMIZA Y REPARA TABLAS MYISAM( LAS RECONSTRUYE)
        - MYISAMPACK: CREA TABLAS MYISAM COMPACTADAS QUE SERAN USADAS ¡SOLO PARA LECTURA NO ES POSIBLE HACER INSERCCION A ALAS TABLAS
						(MEJOR DESEMPEÑO PARA LECTURA)
		- MYISAM_FTDUMP: EXHIVE INFORMACIONAS MAS COMPLETA DE LOS CAMPOS DE TIPO TETXTO
*/

/*	-------------MECANISMOS DE ALMACENAMIENTO PARA TABLAS INNODB--------------------------------
		- MECANISMO DE LAMACENAMIENTO TRANSACCIONAL MAS UTILIZADO EN MYSQL.
			(SI ESTA DISEÑADO PARA QUE VARIOS USUARIOS REALICEN OPERACIONES EN LAS TABLAS SIMULTANEAMENTE)
		- SOPOERTE TRANSACCIONAL COMPLETO / SOPOERTE A CALVEX ECTERNAS
        - CACHE DE BUFFER CONFIGURADO DE FORMA SEPARADA TANTO PARA LAS BASES COMO PARA EL IDNCIE
        - BLOQUEO DE TABL A NIVEL DE LINEA
        - INDEXACION BTREE
        BACK-UP DE BBDDD ONLIE- SIN BLOQUEO DE BBDD
	---------------------- INNODB - VARIABLES DE AMBIENTE -----------------------------------------------
    -----TABLAS
			--- INNODB_DATA_FILE_PAH: DETERMINA CAMINO Y TAMAÑO MAXIMO DEL ARCHIVO DENTRO DEL SISTEMA DONDE SE ALAMCENARA LA INFORMACION
            --- INNODB_DATA_HOME_DIR: CAMINO COMUN DEL DIRECTORIO DE TODOS LOS ARCHIVOS INNODB, CUANDO SE ESPECIFICA, SE GRABA TODO DENTRO DE ESTE DIRECTORIO
					" * DEFAULT = / MYSQLDATA"
			--- INNODB_FILE_PER_TABLE: SEPARA EL ALMACENAMIENTO DE LOS DATOS Y SUS INDICES
					POR DEFECTO ALMACENA DATOS E INDICES DE FORMA COMPARTIDA
	 -----DESEMPEÑO 
			--- INNODB_BUFFER_POLL_SIZE: DETERMINA EL TAMAÑO DE ALMACENAMIENTO QUE INNODB VA A USAR PARA ALMACENAR INDICES Y DATOS EN cache
            --- INNODB_FLUSH_LOG_AT_TRX_COMMIT: DETERMINA LA FECUENCUA CON QUE EL BUFFER DE LOG-IN ES HABILITADO PARA EL DISCO, CRECE CON EL UUSO Y DESPUES DE UN PALS ES DESCARGADO AL HD
            --- INNODB_LOG_FILE_SIZE : TAMAÑO EN BYTES CON EL CUAL SE CREARAN LOS ARCHIVOS DE LOG-IN. POR DEFECTO ES 5MB
*/


/*-------------MECANISMOS DE ALMACENAMIENTO PARA TABLAS MEMORY--------------------------------
		- MECANISMO DE ALMACENAMIENTO QUE CREA TABLAAS EN MEMORIA RAM. NO EN DISCO
        - NO SPORTA CLAVE EXTERNA
        - ACCESO MYT RAPIDO A LA INFORMACION
        - LOS DATOS NECESITAN SER REINICIALIZADOS JUNTO CON EL SERVIDOR
        - BLOQUE A NUVEL DE TABLA
        -INDICES UTIILIZA HASH POR DEFECTO Y BTREE
        - FORMATO DE LINEA DE LONGITUD FIJA( NO SOPORTA BLOB /  TEXT)



*/


