/*
----------------------------------------CLASE 5 BAC-UP DE LA BASE DE DATOS--------------------------------------------

	- ES UNA COPIA DE SEGURIDAD DE LA BASE QUE SE REALIZA PERIDOICAMENTE PARA RECUPERARLA EN CASO DE PROBLEMAS CON LA MISMA

	-------- 2 TIPOS DE BACK-UPS-------------
		BACK-UP LOGICO
			- EXPORTA TODOAS LAS ESTRUCTURAS, TABLAS, RUTINAS(.... ) A UN SCRIPT SQL QUE AL SER EJECUTADO RECREA LA BASE DE DATOS.
            - PERMITE LA MANIPULACION EXTERNA, ANTES DE RECUPERAR LA INFORMACION
            - DESVENTAJE: ES MAS LENTO  EN CUANTO A SU EJECUCION POR EL HECHO DE EJECTUAR COMANDO A COMANDO
		
        BACL-UP FISICO
			-  CONTIENE TODOS LOS ARCHIVOS BINARIOS DEL SISTEMA DONDE LA INFORMACION ESTA ALAMNCENADA, PERO SIN LOS RESPECTIVOS COMANDOS
            - ES MAS RAPIDO QUE EL BACK-UP LOGICO, PERO ES MENOS FLEXIBLE ( NO PERMITE EDITAR TABLAS Y DATOS ANTES DE SU RESTAURACION)
            
		MYSQLDUMO: PARA CREAR BACK-UPS LOGICOS
			- SINTAXIS: MYSQLDUMP [OPTIONS]
            
            - USUARIO, CONTRASEÑA, SERVIDOR
				-  --ALL-DATABASES INDICA QUE EL BACK-UP SERA COMPLETO
                - > <NOMBRE_ARCHIVO> MUESTRA EL ARCHIVO DE SALIDA DEL BACK-UP
                - SE DESEA INCLUIR STORED PROCEDURES Y EVENTOS A USAR
						--   --ROUTINES   --EVENTS
				- https://dev.mysql.com/doc/refman/8.4/en/mysqldump.html
*/
-- COMANDO PARA BLOQUEAR EL SERVIO DE MYSQL Y PODER HACER EL BACKUP
lock instance for backup;


-- COMMANDO PARA QUITAR EL BLOQUEO 
UNLOCK INSTANCE;