/*
CLASE 4 USNADO MECANISMOS DE ALMACENAMIENTO
*/

USE sakila;

CREATE TABLE IF NOT EXISTS df_table(
	ID INT NOT NULL,
    NOMBRE VARCHAR(100));
    
    CREATE TABLE `df_table` (
  `ID` int NOT NULL,
  `NOMBRE` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE df_table ENGINE = MyISAM;

CREATE TABLE IF NOT EXISTS df_table1(
  ID int NOT NULL,
  NOMBRE varchar(100)
) ENGINE = MEMORY;

SHOW engines;

CREATE DATABASE IF NOT EXISTS base;

SHOW VARIABLES WHERE Variable_name LIKE '%dir'
