-- CREANDO BASE DE DATOS
 -- SCADO DE LA DOCUMENTACION DE LA PAGINA OFICILA DE MYSQL
 /*
 --  COMANDO PARA CREAR UNA BASE DE DATOS UN ESQUEMA 
 CREATE {DATABASE | SCHEMA} [IF NOT EXISTS] db_name
		[create_option] ...
		create_option: [DEFAULT] {
			CHARACTER SET [=] charset_name
		  | COLLATE [=] collation_name
		  | ENCRYPTION [=] {'Y' | 'N'}
			}
-- COMANDO PARA ELIMINAR UNA BASE DE DATOS
DROP {DATABASE | SCHEMA} [IF EXISTS] db_name
*/

-- CREAR UNA BASE DE DATOS
CREATE DATABASE IF NOT EXISTS ventas_jugos;
USE ventas_jugos;

-- COMANDO SIMILIAR PARA CREAR UNA BASE DE DATOS
-- NOTA: ESQUEMA Y BASE DE DATOS SON SIMILARES
CREATE SCHEMA IF NOT EXISTS ventas_jugos2;
USE ventas_jugos2;

DROP DATABASE ventas_jugos2;

CREATE SCHEMA IF NOT EXISTS ventas_jugos2 DEFAULT CHARSET utf32;

/* creacion de tablas
	CREATE [TEMPORARY] TABLE [IF NOT EXISTS] tbl_name
    (create_definition,...)
    [table_options]
    [partition_options]

CREATE [TEMPORARY] TABLE [IF NOT EXISTS] tbl_name
    [(create_definition,...)]
    [table_options]
    [partition_options]
    [IGNORE | REPLACE]
    [AS] query_expression

CREATE [TEMPORARY] TABLE [IF NOT EXISTS] tbl_name
    { LIKE old_tbl_name | (LIKE old_tbl_name) } */
    
-- comando para seleccionar la base de datos a trabajar
USE ventas_jugos;

-- crearemos una tabl de vendedores y prodctos
CREATE TABLE IF NOT EXISTS tb_vendedor(
	MATRICULA VARCHAR(5) NOT NULL,
    NOMBRE VARCHAR(100) NULL,
    BARRIO VARCHAR(50) NULL, 
    COMISION FLOAT NULL,
    FECHA_ADMISION DATE NULL,
    DE_VACACIONES BIT(1) NULL,    
    PRIMARY KEY(MATRICULA)
);

CREATE TABLE IF NOT EXISTS tb_producto(
	CODIGO VARCHAR(10) NOT NULL,
    DESCRIPCION VARCHAR(100) NULL,
    SABOR VARCHAR(50) NULL,
    TAMANO VARCHAR(50) NULL,
    ENVASE VARCHAR(50) NULL,
    PRECIO_LISTA FLOAT NULL, 
    PRIMARY KEY(CODIGO)
);

CREATE TABLE IF NOT EXISTS tb_cliente (
  DNI varchar(11) NOT NULL,
  NOMBRE varchar(100) DEFAULT NULL,
  DIRECCION varchar(150) DEFAULT NULL,
  BARRIO varchar(50) DEFAULT NULL,
  CIUDAD varchar(50) DEFAULT NULL,
  ESTADO varchar(45) DEFAULT NULL,
  CP varchar(8) DEFAULT NULL,
  FECHA_NACIMIENTO date DEFAULT NULL,
  EDAD int(2) DEFAULT NULL,
  SEXO varchar(1) DEFAULT NULL,
  LIMITE_CREDITO float DEFAULT NULL,
  VOLUMEN_COMPRA float DEFAULT NULL,
  PRIMERA_COMPRA bit(1) DEFAULT NULL,
  PRIMARY KEY (DNI));

CREATE TABLE IF NOT EXISTS tb_venta(
	NUMERO VARCHAR(5) NOT NULL,
    FECHA DATE NULL, 
    DNI VARCHAR(11) NOT NULL,
    MATRICULA VARCHAR(5) NOT NULL,
    IMPUESTO FLOAT ,
    PRIMARY KEY (NUMERO)    
);

ALTER TABLE tb_venta ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (DNI) REFERENCES tb_cliente(DNI);
ALTER TABLE tb_venta ADD CONSTRAINT FK_VENDEDOR FOREIGN KEY (MATRICULA) REFERENCES tb_vendedor(MATRICULA);

USE ventas_jugos;
ALTER TABLE tb_venta RENAME tb_factura;

CREATE TABLE items_factura(
	NUMERO VARCHAR(5) NOT NULL,
	CODIGO VARCHAR(10) NOT NULL,
	CANTIDAD INT,
	PRECIO FLOAT,
	PRIMARY KEY (NUMERO, CODIGO)
);

ALTER TABLE items_factura ADD CONSTRAINT FK_FACTURA FOREIGN KEY (NUMERO) REFERENCES tb_factura(NUMERO);

ALTER TABLE items_factura RENAME tb_item_factura;

ALTER TABLE tb_item_factura ADD CONSTRAINT FK_PRODUCTO FOREIGN KEY (CODIGO) REFERENCES tb_producto(CODIGO);