/*
			------------------------ PLAN DE EJECUCION----------------------------------------
				OPTIMIZACION Y DESEMPÑEO DE LAS CONSULTAS
                EL DBA DEBE AUXILIAR AL ANALISTA EN EL MEJORAMIENTO DEL DESEMPEÑO DE LAS CONULTAS A ÑLA BDD
                VERIFICAR EL TIEWMPO DE EJECUCION DE UNA CONSULTA
*/

-- TIEMPO DE EJECCUCION 00.00 SEC
SELECT A.CODIGO_DEL_PRODUCTO FROM tabla_de_productos A;

-- TIEMPO DE EJECUCION 0.156 SEC
SELECT A.CODIGO_DEL_PRODUCTO,  C.CANTIDAD FROM tabla_de_productos A
INNER JOIN items_facturas C
ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO;

-- TIEMPO DE EJECUCION 0.015 SEC
SELECT A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA) AS ANIO ,C.CANTIDAD FROM tabla_de_productos A
INNER JOIN items_facturas C
ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F 
ON C.NUMERO = F.NUMERO;


-- TIEMPO DE EJECUCION 2.67 SEC
SELECT A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA) AS ANIO , SUM(C.CANTIDAD) AS CANTIDAD FROM tabla_de_productos A
INNER JOIN items_facturas C
ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F 
ON C.NUMERO = F.NUMERO
GROUP BY A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA)
ORDER BY A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA);

