/*
			CLASE 03 TRABAJANDO CON IDNCIES Y MYSQLSLAP
PLAN DE EJECUCION
CREAR Y MEJORAR UN INDICE
*/

-- TIEMPO DE EJECCUCION 00.00 SEC  EXPLAIN FORMAT= JSON
 SELECT A.CODIGO_DEL_PRODUCTO FROM tabla_de_productos A;
-- EN CONSOLA EL COST ES DE 4.50

-- TIEMPO DE EJECUCION 0.156 SEC
SELECT A.CODIGO_DEL_PRODUCTO,  C.CANTIDAD FROM tabla_de_productos A INNER JOIN items_facturas C ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO;
-- EN CONSOLA EL COST ES DE 84859.54

-- TIEMPO DE EJECUCION 0.015 SEC
SELECT A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA) AS ANIO , C.CANTIDAD FROM tabla_de_productos A INNER JOIN items_facturas C ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO INNER JOIN facturas F ON C.NUMERO = F.NUMERO;
-- EN CONSOLA EL COST ES DE 388789.95

-- TIEMPO DE EJECUCION 2.67 SEC
SELECT A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA) AS ANIO , SUM(C.CANTIDAD) AS CANTIDAD FROM tabla_de_productos A INNER JOIN items_facturas C ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO INNER JOIN facturas F ON C.NUMERO = F.NUMERO GROUP BY A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA) ORDER BY A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA);
-- COST 388789.98



CREATE TABLE `facturas1` (
  `DNI` varchar(11) NOT NULL,
  `MATRICULA` varchar(5) NOT NULL,
  `FECHA_VENTA` date DEFAULT NULL,
  `NUMERO` int NOT NULL,
  `IMPUESTO` float NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `items_facturas1` (
  `NUMERO` int NOT NULL,
  `CODIGO_DEL_PRODUCTO` varchar(10) NOT NULL,
  `CANTIDAD` int NOT NULL,
  `PRECIO` float NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `tabla_de_productos1` (
  `CODIGO_DEL_PRODUCTO` varchar(10) NOT NULL,
  `NOMBRE_DEL_PRODUCTO` varchar(50) DEFAULT NULL,
  `TAMANO` varchar(10) DEFAULT NULL,
  `SABOR` varchar(20) DEFAULT NULL,
  `ENVASE` varchar(20) DEFAULT NULL,
  `PRECIO_DE_LISTA` float NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO facturas1 SELECT * FROM facturas;

INSERT INTO items_facturas1 SELECT * FROM items_facturas;

INSERT INTO tabla_de_productos1 SELECT * FROM tabla_de_productos;


-- TIEMPO DE EJECCUCION 00.00 SEC  EXPLAIN FORMAT= JSON
 EXPLAIN FORMAT= JSON SELECT A.CODIGO_DEL_PRODUCTO FROM tabla_de_productos1 A;
SELECT A.CODIGO_DEL_PRODUCTO FROM tabla_de_productos1 A;
-- EN CONSOLA EL COST ES DE 4.50

-- TIEMPO DE EJECUCION 0.156 SEC
SELECT A.CODIGO_DEL_PRODUCTO,  C.CANTIDAD FROM tabla_de_productos1 A INNER JOIN items_facturas1 C ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO;
EXPLAIN FORMAT= JSON SELECT A.CODIGO_DEL_PRODUCTO,  C.CANTIDAD FROM tabla_de_productos1 A INNER JOIN items_facturas1 C ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO;
-- EN CONSOLA EL COST ES DE 84859.54

-- TIEMPO DE EJECUCION 0.015 SEC
SELECT A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA) AS ANIO , C.CANTIDAD FROM tabla_de_productos1 A INNER JOIN items_facturas1 C ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO INNER JOIN facturas1 F ON C.NUMERO = F.NUMERO;
EXPLAIN FORMAT= JSON SELECT A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA) AS ANIO , C.CANTIDAD FROM tabla_de_productos1 A INNER JOIN items_facturas1 C ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO INNER JOIN facturas1 F ON C.NUMERO = F.NUMERO;
-- EN CONSOLA EL COST ES DE 388789.95

-- TIEMPO DE EJECUCION 2.67 SEC
EXPLAIN FORMAT= JSON SELECT A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA) AS ANIO , SUM(C.CANTIDAD) AS CANTIDAD FROM tabla_de_productos1 A INNER JOIN items_facturas1 C ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO INNER JOIN facturas1 F ON C.NUMERO = F.NUMERO GROUP BY A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA) ORDER BY A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA);
SELECT A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA) AS ANIO , SUM(C.CANTIDAD) AS CANTIDAD FROM tabla_de_productos1 A INNER JOIN items_facturas1 C ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO INNER JOIN facturas1 F ON C.NUMERO = F.NUMERO GROUP BY A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA) ORDER BY A.CODIGO_DEL_PRODUCTO, YEAR(F.FECHA_VENTA);
-- COST 388789.98

-- coste 25.90
SELECT *FROM facturas WHERE FECHA_VENTA = "20170101";


-- coste 8864.55
SELECT *FROM FACTURAS1 WHERE FECHA_VENTA = "20170101";